### ISSUE TITLE
can I send a pull-request?

### ISSUE THREAD

**Issue by rocaltair** [JerryZhou/aoi#1]
a nice lib!

but it can't be compatible with c89(and only on Mac?)
I made some changes, and add a lib for [lua-wrap](https://github.com/rocaltair/aoi/blob/master/laoi.c)(so far so good) [test.lua](https://github.com/rocaltair/aoi/blob/master/test.lua) 

It can be run on Mac/Linux(see [Makefile](https://github.com/rocaltair/aoi/blob/master/Makefile)) /Windows([msvc_build.bat](https://github.com/rocaltair/aoi/blob/master/msvc_build.bat))

see [changes](https://github.com/JerryZhou/aoi/compare/master...rocaltair:master)

**Comment by JerryZhou** [comment]
sorry for reply later, 

thanks for your contributes

offcourse, you can push changes.

**Comment by rocaltair** [comment]
That's my honor~
